### ISSUE TITLE
Given a version, list possible next versions?

### ISSUE THREAD

**Issue by mholt** [wmark/semver#5]
Thanks for this lib, Mark. I'm wondering if you'd entertain a discussion (even a brief one) about the possibility of a function that takes as input a semantic version and returns a list of (reasonable) possible next versions.

In other words, given this:

```
"v1.0.0"
```

The function might return:

```
[]string{"v1.0.1", "v1.1.0", "v2.0.0"}
```

And (optionally?) some pre-release "next" versions as well. I'm using this to prompt a user what to tag a commit as.

Would this function have a place in your lib?

**Comment by wmark** [comment]
Sure, we can do that.

This most likely will be a low-volume–call kind of function, so its signature doesn't need to be perfect and the implementation does not need to be a 0-alloc one. But I'd suggest going with return type `[]semver.Version`. Then we'd (or I) implement a `Version.ToString()` or similar subsequently.

If you want to implement this and file a PR, please mention if and when I should finish it. (Fill-or-kill at (Mark implements) 0%–100% (review only).)

BTW, you don't need this in an auto-updater, to check if an update (higher version number in a *git tag*) is available. `Version.IsAPreRelease` and `Version.Less` will do the job.

**Comment by mholt** [comment]
@wmark Thanks! I'll see if I can hack on it this week, it's not an urgent need, but I wanted to file this before I forgot.

> BTW, you don't need this in an auto-updater

Correct; this is for my deployment system.

**Comment by wmark** [comment]
Alright. Push an empty commit when you've started. Or go through the PRs. I've already an implementation in mind, but in the end you express your expectations through test.

FYI: Friday start the *Giro d'Italia*, then there's the *Big Brother Awards*, and after that *Re:Publica*. You picked an busy weekend. ;-)
